{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zabbix.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "zabbix.serviceAccountName" . }}
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
type:  kubernetes.io/service-account-token
{{- end}}
